INSERT INTO ROLE  (TIPO) VALUES ('ADMIN');
INSERT INTO ROLE  (TIPO) VALUES ('ADMIN');

INSERT INTO USUARIO  (NOME, EMAIL, SENHA) VALUES ('ANDERSON', 'ANDER@GMAIL', '1234');
INSERT INTO USUARIO  (NOME, EMAIL, SENHA) VALUES ('CARLOS', 'ANDER@GMAIL', '1234');

INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES (1,1);
INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES (1,2);

