INSERT INTO ESCOLA (NOME) VALUES ('ESCOLA TESTE 1');
INSERT INTO ESCOLA (NOME) VALUES ('ESCOLA TESTE 2');
INSERT INTO ESCOLA (NOME) VALUES ('ESCOLA TESTE 3');

INSERT INTO TB_ALUNO ( NOME, escola_id) VALUES ('ALUNO DE TESTE', 1);